export default {
  AMI: 'Acute Myocardial Infarction',
  CHD: 'Congenital Heart Disease',
  CHF: 'Congenital Heart Failure',
  AF: 'Atrial Flutter',
  Af: 'Atrial Fibrillation',
  VF: 'Ventricular Flutter',
  VT: 'Ventricular Tachycardia',
  CAD: 'Coronary Artery Disease',
  'H/T': 'Hypertension',
  RHD: 'Rheumatic Heart Disease',
  SLE: 'Systemic Lupus Erythematosus',
  DIC: 'Disseminated Intravascular Coagulation',
  COPD: 'Chronic Obstructive  Pulmonary  Disease',
  PE: 'Pulmonary Embolism ',
  SOB: 'short of breath',
  URI: 'Upper Respiratory Infection',
  ARF: 'Acute Renal Failure',
  'App.': 'Appendicitis',
  HHNK: 'Hyperglycemic Hyperosmolar Nonketolytic Coma',
  DM: 'diabetes mellitus',
  CP: 'Cerebral Palsy',
  IICP: 'Increased Intracranial Pressure',
  HIVD: 'Herniation of Intervertebral Disc',
  MS: 'Multiple Sclerosis',
  MG: 'Myasthenic Ggravis',
  RA: 'Rreumatoid Arthritis',
  BPH: 'benign prostatic hypertrophy',
  UTI: 'Urinary Tract Infection',
  NPC: 'Nasopharyngeal Carcinoma',
  CPS: 'Chronic paranasal sinusitis',
  RD: 'Retinal Detachment',
  IVF: 'In Vitro Fertilization',
  AFE: 'Amniotic Fluid Embolism',
  VD: 'Venereal Disease',
  PROM: 'Premature Rupture of  Membrane',
  RDS: 'Respiratory Distress Syndrome',
  SAH: 'Subarachnoid Hemorrhage',
  LE: 'Lupus erythematosus',
  TB: 'Tuberculosis',
  Ca: 'potassium',
  CPN: 'chronic pyelonephritis ',
  DOA: 'dead on arrival',
  DOE: 'dyspnea on exercise',
  AGN: 'Acute Glomerulenephritis',
  LP: 'Lumbar Puncture',
  THR: 'Total Hip Replacement',
  'D&C': 'Dilatation and Curettage',
  'D&E': 'Dilatation and Evacuation',
  EP: 'Episiotomy',
  CVP: 'central venous pressure',
  'B.T.': 'Transfusion',
  GCS: 'Glasgow Coma scale',
  ROM: 'Range of  Motion',
  PP: 'Postpartum',
  'C/S': 'Cesarean Section',
  NSD: 'Normal Spontaneous Delivery',
  AAD: 'against-advice discharge',
  BW: 'body  weight',
  CC: 'chief complaint',
  CO: 'cardiac output',
  CPR: 'cardiopulmonary resuscitation',
  BH: 'body height',
  OU: 'Oculus Uterque',
  OS: 'Oculus Sinister',
  OD: ' Oculus Dexter',
  'I&O': 'Intake and output',
  KUB: 'kidney',
  MBD: 'ureter',
  NPO: 'bladder',
  OP: 'may be discharged',
  OPD: 'according to ',
  'R/O': 'operation',
  'p.o': 'outpatient department',
  'a.c': 'rule out',
  'p.c': 'by mouth',
  'h.s': 'before meal',
  'p.r.n': 'after meals',
  'q.h': 'at  bedtime',
  'q.d': 'as needed',
  'b.i.d': 'every hour',
  't.i.d': 'every day',
  'q.i.d': 'twice a day',
  DC: 'three time a day',
  K: 'four times a day',
  Na: 'discontinue',
  Fe: 'sodium',
  Mg: 'calcium',
  Li: 'iron',
  P: 'magnesium',
  'sp. gr.': 'lithium',
  ECG: 'Laryngoscopy',
  EEG: 'Laparoscope',
  'Pap Smear': 'Angiogaphy',
  FHS: 'Colonoscopy',
  CT: 'Papanicolaou Smear',
  LMD: 'conventional tomography',
  cc: 'Local medical doctor',
  'c/o': 'Local medical doctor',
  ER: 'family history',
  DR: 'chief complaint',
  Derm: 'emergency room',
  CVS: 'delivery room',
  OBS: 'dermatology',
  ENT: 'cardiovascular surgery',
  GU: 'obstetrics',
  GYN: 'ear',
  BR: 'nose',
  WBC: 'Gynecology',
  RBC: 'Erythrocyte',
  Hb: 'Leukocyte',
  CCr: 'white blood cell',
  CRP: 'platelet',
  CSF: 'red blood cell',
  'Hct.': 'hemoglobin',
  ICU: 'local clinic ',
  'B.S.': 'general appearance',
  'Pre-OP': 'due to ',
  'Post-OP': 'breathing sound'
}
